import { SendIcon } from '@/components/Icons'
// import { TypingEffect } from '@/components/TypingEffect'
import Head from 'next/head'
import { useMessageStore } from '@/store/messages'
import { useRef } from 'react'
import { DeleteButton } from '@/components/DeleteButton'

function Layout ({ children }) {
  return (
    <>
      <Head>
        <title className='hola'>Castro Bot</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div id='chat' className='w-full relative bg-black h-screen text-slate-50 overflow-y-auto'>
        {/* <Aside /> */}
        {children}
      </div>
    </>
  )
}

function UserAvatar () {
  return (
    <img
      className=' rounded-md bg-black'
      alt='foto de david'
      src='https://www.davidcastro.tech/static/images/david.jpg'
    />
  )
}

function IaAvatar () {
  return (
    <i className='fa-solid fa-robot' />
  )
}

function Message ({ ia, message }) {
  const avatar = ia ? <IaAvatar /> : <UserAvatar />
  const lines = message.split('\n')
  const messageList = lines.map((line, index) => (
  //  <p key={index}>{ia ? <TypingEffect text={line} /> : message}</p>
    <p key={index}>{line}</p>
  ))

  return (
    <div>
      <article className='flex gap-4 p-6 m-auto max-w-3xl text-gray-100 '>
        <figure className={`${ia ? ' bg-purple-700' : ' bg-black'} w-8 h-8 flex items-center justify-center rounded-md`}>
          {avatar}
        </figure>
        <div className=' flex-1'>
          <p className={`${ia ? ' bg-purple-700' : ' bg-green-700'} rounded-md p-4`}>
            {messageList}
          </p>
        </div>
      </article>
    </div>
  )
}

function Chat () {
  const messages = useMessageStore(state => state.messages)

  return (
    <div className='flex flex-col h-full flex-1'>
      <ChatForm />
      <main id='chat' className=' mt-[180px]'>
        {messages.map((entry) => (
          <Message key={entry.id} {...entry} />
        ))}
        <DeleteButton />
      </main>
    </div>
  )
}

function ChatForm () {
  const sendPrompt = useMessageStore(state => state.sendPrompt)
  const textAreaRef = useRef()
  const messages = useMessageStore(state => state.messages)

  const handleSubmit = (event) => {
    let prompts = ''
    messages.map((entry) => (
      prompts += entry.message
    ))

    prompts += textAreaRef.current.value
    event.preventDefault()
    sendPrompt({ prompt: prompts, userPrompt: textAreaRef.current.value })
    textAreaRef.current.value = ''
  }

  const handleChange = () => {
    const el = textAreaRef.current
    const scrollHeight = el.scrollHeight
    el.style.height = scrollHeight + 'px'
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit(e)
    }
  }

  return (
    <div className='w-full fixed top-0 bg-black'>
      <section className=' m-4 justify-center bg-neutral-900 border-neutral-600 border-2 rounded-lg p-3 pb-7'>
        {/* <img src='./public/CASTROBOT.svg' width='200' height='200' alt='logo' /> */}
        <h1 className=' text-center text-3xl pb-3'>CastroBot</h1>
        <form
          onSubmit={handleSubmit}
          onKeyDown={handleKeyDown}
          className=' w-full m-auto'
        >
          <div className='relative flex flex-col py-3 px-4 border flex-grow
        border-gray-900/50 text-white bg-gptlightgray rounded-md '
          >
            <textarea
              onChange={handleChange}
              ref={textAreaRef}
              rows={1}
              tabIndex={0}
              autoFocus
              defaultValue=''
              placeholder='Ask me something'
              className='h-[24px] resize-none bg-transparent border-0 outline-none'
            />
            <button className='absolute p-1 rounded-md bottom-2.5 right-2.5'>
              <SendIcon />
            </button>
          </div>
        </form>
      </section>
    </div>
  )
}

export default function Home () {
  return (
    <>
      <Layout>
        <Chat />
      </Layout>
      <script src='https://kit.fontawesome.com/a654d59b05.js' crossorigin='anonymous' async />
    </>
  )
}
